// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QrBancoEconomico.Infrastructure;

#nullable disable

namespace QrBancoEconomico.Infrastructure.Migrations
{
    [DbContext(typeof(BanecoDbContext))]
    [Migration("20260906211001_AddBanecoAccountInventory")]
    partial class AddBanecoAccountInventory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QrBancoEconomico.Domain.BanecoAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountCodeEncrypted")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("BatchDebitAccountEncrypted")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CredentialRef")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("BanecoAccounts", (string)null);
                });

            modelBuilder.Entity("QrBancoEconomico.Domain.BatchUpload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountCodeEncrypted")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("BanecoAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("BankBatchId")
                        .HasColumnType("bigint");

                    b.Property<string>("BatchId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DetailedDebit")
                        .HasColumnType("bit");

                    b.Property<int>("PaymentCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("SubscriberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BanecoAccountId", "BatchId")
                        .IsUnique()
                        .HasFilter("[BanecoAccountId] IS NOT NULL");

                    b.HasIndex("SubscriberId", "BatchId")
                        .IsUnique()
                        .HasFilter("[SubscriberId] IS NOT NULL");

                    b.ToTable("BatchUploads", (string)null);
                });

            modelBuilder.Entity("QrBancoEconomico.Domain.QrPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BranchCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<string>("PaymentTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QrId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("QrTransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SenderAccount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderBankCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderDocumentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QrTransactionId");

                    b.ToTable("QrPayments", (string)null);
                });

            modelBuilder.Entity("QrBancoEconomico.Domain.QrTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountCreditEncrypted")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("BanecoAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BankQrId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BranchCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("MerchantTransactionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("ModifyAmount")
                        .HasColumnType("bit");

                    b.Property<string>("QrImageBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SingleUse")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("SubscriberId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BankQrId")
                        .IsUnique()
                        .HasFilter("[BankQrId] IS NOT NULL");

                    b.HasIndex("BanecoAccountId", "MerchantTransactionId")
                        .IsUnique()
                        .HasFilter("[BanecoAccountId] IS NOT NULL");

                    b.HasIndex("SubscriberId", "MerchantTransactionId")
                        .IsUnique()
                        .HasFilter("[SubscriberId] IS NOT NULL");

                    b.ToTable("QrTransactions", (string)null);
                });

            modelBuilder.Entity("QrBancoEconomico.Domain.Subscriber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RequestsPerMinute")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Subscribers", (string)null);
                });

            modelBuilder.Entity("QrBancoEconomico.Domain.SubscriberApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<byte[]>("SecretHash")
                        .IsRequired()
                        .HasColumnType("varbinary(32)");

                    b.Property<Guid>("SubscriberId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("SubscriberId");

                    b.ToTable("SubscriberApiKeys", (string)null);
                });

            modelBuilder.Entity("QrBancoEconomico.Domain.SubscriberBanecoAccount", b =>
                {
                    b.Property<Guid>("SubscriberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BanecoAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("GrantedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.HasKey("SubscriberId", "BanecoAccountId");

                    b.HasIndex("BanecoAccountId");

                    b.HasIndex("SubscriberId")
                        .IsUnique()
                        .HasDatabaseName("UX_SubscriberBanecoAccounts_Default")
                        .HasFilter("[IsDefault] = 1");

                    b.ToTable("SubscriberBanecoAccounts", (string)null);
                });

            modelBuilder.Entity("QrBancoEconomico.Domain.BatchUpload", b =>
                {
                    b.HasOne("QrBancoEconomico.Domain.BanecoAccount", "BanecoAccount")
                        .WithMany()
                        .HasForeignKey("BanecoAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QrBancoEconomico.Domain.Subscriber", "Subscriber")
                        .WithMany()
                        .HasForeignKey("SubscriberId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BanecoAccount");

                    b.Navigation("Subscriber");
                });

            modelBuilder.Entity("QrBancoEconomico.Domain.QrPayment", b =>
                {
                    b.HasOne("QrBancoEconomico.Domain.QrTransaction", "QrTransaction")
                        .WithMany("Payments")
                        .HasForeignKey("QrTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QrTransaction");
                });

            modelBuilder.Entity("QrBancoEconomico.Domain.QrTransaction", b =>
                {
                    b.HasOne("QrBancoEconomico.Domain.BanecoAccount", "BanecoAccount")
                        .WithMany()
                        .HasForeignKey("BanecoAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QrBancoEconomico.Domain.Subscriber", "Subscriber")
                        .WithMany()
                        .HasForeignKey("SubscriberId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BanecoAccount");

                    b.Navigation("Subscriber");
                });

            modelBuilder.Entity("QrBancoEconomico.Domain.SubscriberApiKey", b =>
                {
                    b.HasOne("QrBancoEconomico.Domain.Subscriber", "Subscriber")
                        .WithMany("ApiKeys")
                        .HasForeignKey("SubscriberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscriber");
                });

            modelBuilder.Entity("QrBancoEconomico.Domain.SubscriberBanecoAccount", b =>
                {
                    b.HasOne("QrBancoEconomico.Domain.BanecoAccount", "BanecoAccount")
                        .WithMany("Subscribers")
                        .HasForeignKey("BanecoAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QrBancoEconomico.Domain.Subscriber", "Subscriber")
                        .WithMany("Accounts")
                        .HasForeignKey("SubscriberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BanecoAccount");

                    b.Navigation("Subscriber");
                });

            modelBuilder.Entity("QrBancoEconomico.Domain.BanecoAccount", b =>
                {
                    b.Navigation("Subscribers");
                });

            modelBuilder.Entity("QrBancoEconomico.Domain.QrTransaction", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("QrBancoEconomico.Domain.Subscriber", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("ApiKeys");
                });
#pragma warning restore 612, 618
        }
    }
}
